'use client';

import Link from 'next/link';
import { useAuth } from '../hooks/useAuth';
import { useEffect, useRef, useState } from 'react';

const TYPING_PHRASES = [
  'Cold Emails That Convert',
  'Personalized Outreach at Scale',
  'Sales Pitches in Seconds',
  'Emails That Get Replies',
];

function useTypewriter(phrases: string[], speed = 80, pause = 1800) {
  const [displayed, setDisplayed] = useState('');
  const [phraseIdx, setPhraseIdx] = useState(0);
  const [charIdx, setCharIdx] = useState(0);
  const [deleting, setDeleting] = useState(false);

  useEffect(() => {
    const current = phrases[phraseIdx];
    let timeout: ReturnType<typeof setTimeout>;

    if (!deleting && charIdx <= current.length) {
      timeout = setTimeout(() => {
        setDisplayed(current.slice(0, charIdx));
        setCharIdx((i) => i + 1);
      }, speed);
    } else if (!deleting && charIdx > current.length) {
      timeout = setTimeout(() => setDeleting(true), pause);
    } else if (deleting && charIdx >= 0) {
      timeout = setTimeout(() => {
        setDisplayed(current.slice(0, charIdx));
        setCharIdx((i) => i - 1);
      }, speed / 2);
    } else {
      setDeleting(false);
      setPhraseIdx((i) => (i + 1) % phrases.length);
    }

    return () => clearTimeout(timeout);
  }, [charIdx, deleting, phraseIdx, phrases, speed, pause]);

  return displayed;
}

function useScrollReveal() {
  const ref = useRef<HTMLDivElement>(null);
  const [visible, setVisible] = useState(false);

  useEffect(() => {
    const el = ref.current;
    if (!el) return;
    const observer = new IntersectionObserver(
      ([entry]) => { if (entry.isIntersecting) setVisible(true); },
      { threshold: 0.15 }
    );
    observer.observe(el);
    return () => observer.disconnect();
  }, []);

  return { ref, visible };
}

function RevealSection({ children, className = '', delay = 0 }: { children: React.ReactNode; className?: string; delay?: number }) {
  const { ref, visible } = useScrollReveal();
  return (
    <div
      ref={ref}
      className={className}
      style={{
        opacity: visible ? 1 : 0,
        transform: visible ? 'translateY(0)' : 'translateY(32px)',
        transition: `opacity 0.7s ease ${delay}ms, transform 0.7s ease ${delay}ms`,
      }}
    >
      {children}
    </div>
  );
}

const FEATURES = [
  { icon: '🤖', title: 'AI-Powered', desc: 'Claude AI generates hyper-personalized emails tailored to your target audience and industry.' },
  { icon: '⚡', title: 'Lightning Fast', desc: 'Get multiple email variations in seconds. Stop spending hours on outreach copy.' },
  { icon: '🎯', title: 'High Converting', desc: 'Emails crafted with proven frameworks that drive opens, replies, and meetings.' },
  { icon: '📧', title: 'Full Personalization', desc: 'Customize tone, length, style, and target persona for every campaign.' },
  { icon: '📊', title: 'Email Sequences', desc: 'Generate entire multi-step follow-up sequences, not just one-off emails.' },
  { icon: '🔐', title: 'Privacy First', desc: 'Your data is encrypted at rest and in transit. We never sell your information.' },
];

const STEPS = [
  { label: 'Sign Up Free', desc: 'Create your account in 30 seconds and receive free tokens instantly.' },
  { label: 'Describe Your Pitch', desc: 'Tell us about your product, target audience, and the tone you want.' },
  { label: 'Get AI Emails', desc: 'Receive multiple personalized email variations generated by AI.' },
  { label: 'Send & Win', desc: 'Copy the best email, hit send, and start booking more meetings.' },
];

const FAQS = [
  {
    q: 'How does PitchPerfect generate emails?',
    a: 'PitchPerfect uses Claude AI (Anthropic) under the hood. You describe your product and target audience, and our AI crafts personalized cold emails using proven outreach frameworks.',
  },
  {
    q: 'Do I need a credit card to get started?',
    a: 'No. Sign up for free and get tokens immediately — no credit card required. You can explore all core features before deciding to upgrade.',
  },
  {
    q: 'How many emails can I generate per token?',
    a: 'Each generation request costs 1 token and produces up to 3 email variations with different subject lines and approaches, so you get maximum value per token.',
  },
  {
    q: 'Can I customize the tone and style of the emails?',
    a: 'Absolutely. You can choose from Professional, Friendly, Direct, Storytelling, and more. You can also specify the email length and any specific talking points to include.',
  },
  {
    q: 'Are my emails and business data kept private?',
    a: 'Yes. All data is encrypted in transit and at rest. We never share or sell your information, and your generated emails are only visible to you.',
  },
  {
    q: 'Can I generate follow-up email sequences?',
    a: 'Yes! PitchPerfect supports multi-step email sequences. You can generate an initial outreach email plus follow-ups (Day 3, Day 7, Day 14) as a complete campaign.',
  },
  {
    q: 'What industries does PitchPerfect work best for?',
    a: 'PitchPerfect works for SaaS, agencies, freelancers, recruiters, real estate, consulting, and any business that relies on cold outreach to generate leads.',
  },
  {
    q: 'How do I get more tokens when I run out?',
    a: 'Visit the Billing page to top up or upgrade your plan. We offer flexible token packages so you only pay for what you actually use.',
  },
];

function FAQItem({ q, a }: { q: string; a: string }) {
  const [open, setOpen] = useState(false);
  return (
    <div className="border border-gray-200 rounded-xl overflow-hidden">
      <button
        onClick={() => setOpen(!open)}
        className="w-full flex items-center justify-between px-6 py-5 text-left bg-white hover:bg-gray-50 transition-colors"
      >
        <span className="font-semibold text-gray-900 text-base pr-4">{q}</span>
        <span
          className="text-2xl text-indigo-500 flex-shrink-0 transition-transform duration-300"
          style={{ transform: open ? 'rotate(45deg)' : 'rotate(0deg)' }}
        >
          +
        </span>
      </button>
      <div
        style={{
          maxHeight: open ? '300px' : '0',
          opacity: open ? 1 : 0,
          transition: 'max-height 0.4s ease, opacity 0.3s ease',
          overflow: 'hidden',
        }}
      >
        <p className="px-6 pb-5 text-gray-600 leading-relaxed">{a}</p>
      </div>
    </div>
  );
}

export default function HomePage() {
  const { isAuthenticated } = useAuth();
  const typewritten = useTypewriter(TYPING_PHRASES);

  return (
    <div className="overflow-x-hidden">
      <style>{`
        @keyframes float {
          0%, 100% { transform: translateY(0px); }
          50% { transform: translateY(-12px); }
        }
        @keyframes fadeInUp {
          from { opacity: 0; transform: translateY(24px); }
          to { opacity: 1; transform: translateY(0); }
        }
        @keyframes gradientShift {
          0% { background-position: 0% 50%; }
          50% { background-position: 100% 50%; }
          100% { background-position: 0% 50%; }
        }
        @keyframes pulse-ring {
          0% { transform: scale(1); opacity: 0.6; }
          100% { transform: scale(1.6); opacity: 0; }
        }
        .animate-float { animation: float 4s ease-in-out infinite; }
        .animate-fade-in-up { animation: fadeInUp 0.8s ease forwards; }
        .gradient-animated {
          background: linear-gradient(135deg, #1e1b4b, #312e81, #4338ca, #7c3aed, #312e81);
          background-size: 300% 300%;
          animation: gradientShift 8s ease infinite;
        }
        .hero-glow {
          position: absolute;
          border-radius: 50%;
          filter: blur(80px);
          opacity: 0.3;
        }
        .card-hover {
          transition: transform 0.3s ease, box-shadow 0.3s ease;
        }
        .card-hover:hover {
          transform: translateY(-6px);
          box-shadow: 0 20px 40px rgba(99, 102, 241, 0.15);
        }
        .stat-counter {
          background: linear-gradient(135deg, #6366f1, #8b5cf6);
          -webkit-background-clip: text;
          -webkit-text-fill-color: transparent;
          background-clip: text;
        }
      `}</style>

      {/* Hero Section */}
      <section className="gradient-animated text-white pt-28 pb-32 px-4 relative overflow-hidden min-h-screen flex items-center">
        <div className="hero-glow bg-purple-400 w-96 h-96 top-10 -left-20" />
        <div className="hero-glow bg-indigo-400 w-80 h-80 bottom-10 right-10" />
        <div className="hero-glow bg-blue-400 w-64 h-64 top-1/2 left-1/2 -translate-x-1/2" />

        <div className="max-w-5xl mx-auto text-center relative z-10">
          <div
            className="inline-flex items-center gap-2 bg-white/10 backdrop-blur-sm border border-white/20 rounded-full px-5 py-2 text-sm font-medium mb-8"
            style={{ animation: 'fadeInUp 0.6s ease forwards' }}
          >
            <span className="w-2 h-2 bg-green-400 rounded-full animate-pulse inline-block" />
            AI-Powered Cold Email Generator
          </div>

          <h1
            className="text-6xl md:text-7xl font-extrabold mb-6 leading-tight tracking-tight"
            style={{ animation: 'fadeInUp 0.7s ease 0.1s both' }}
          >
            Write{' '}
            <span className="relative">
              <span className="text-yellow-300">{typewritten}</span>
              <span className="animate-pulse text-yellow-300">|</span>
            </span>
          </h1>

          <p
            className="text-xl md:text-2xl text-indigo-200 mb-10 max-w-2xl mx-auto leading-relaxed"
            style={{ animation: 'fadeInUp 0.7s ease 0.2s both' }}
          >
            Stop spending hours on outreach. Let AI craft personalized, high-converting cold emails in seconds — tailored to every prospect.
          </p>

          <div
            className="flex flex-col sm:flex-row gap-4 justify-center"
            style={{ animation: 'fadeInUp 0.7s ease 0.35s both' }}
          >
            {isAuthenticated ? (
              <Link
                href="/generate"
                className="inline-flex items-center gap-2 bg-white text-indigo-700 px-8 py-4 rounded-xl font-bold text-lg hover:bg-indigo-50 transition-all shadow-lg hover:shadow-xl"
              >
                Start Generating
                <span className="text-xl">→</span>
              </Link>
            ) : (
              <>
                <Link
                  href="/signup"
                  className="inline-flex items-center gap-2 bg-white text-indigo-700 px-8 py-4 rounded-xl font-bold text-lg hover:bg-indigo-50 transition-all shadow-lg hover:shadow-xl"
                >
                  Get Started Free
                  <span className="text-xl">→</span>
                </Link>
                <Link
                  href="/login"
                  className="inline-flex items-center gap-2 bg-white/10 backdrop-blur-sm border border-white/30 text-white px-8 py-4 rounded-xl font-bold text-lg hover:bg-white/20 transition-all"
                >
                  Sign In
                </Link>
              </>
            )}
          </div>

          <p
            className="mt-6 text-indigo-300 text-sm"
            style={{ animation: 'fadeInUp 0.7s ease 0.45s both' }}
          >
            Free to start — no credit card required
          </p>

          {/* Floating stats */}
          <div
            className="mt-16 grid grid-cols-3 gap-6 max-w-2xl mx-auto"
            style={{ animation: 'fadeInUp 0.7s ease 0.55s both' }}
          >
            {[
              { value: '10x', label: 'Faster Outreach' },
              { value: '3+', label: 'Email Variations' },
              { value: '100%', label: 'AI Personalized' },
            ].map((stat) => (
              <div key={stat.label} className="bg-white/10 backdrop-blur-sm rounded-2xl p-4 border border-white/20">
                <div className="text-3xl font-extrabold text-white">{stat.value}</div>
                <div className="text-indigo-300 text-sm mt-1">{stat.label}</div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-24 px-4 bg-gray-50">
        <div className="max-w-6xl mx-auto">
          <RevealSection className="text-center mb-16">
            <span className="text-indigo-600 font-semibold text-sm uppercase tracking-widest">Why PitchPerfect</span>
            <h2 className="text-4xl font-extrabold text-gray-900 mt-3 mb-4">Everything You Need to Close More Deals</h2>
            <p className="text-gray-500 text-lg max-w-xl mx-auto">Powerful features that help you write better cold emails, faster.</p>
          </RevealSection>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {FEATURES.map((f, i) => (
              <RevealSection key={f.title} delay={i * 80}>
                <div className="bg-white p-7 rounded-2xl shadow-sm border border-gray-100 card-hover h-full">
                  <div className="text-4xl mb-4 animate-float" style={{ animationDelay: `${i * 0.3}s` }}>{f.icon}</div>
                  <h3 className="text-lg font-bold text-gray-900 mb-2">{f.title}</h3>
                  <p className="text-gray-500 leading-relaxed text-sm">{f.desc}</p>
                </div>
              </RevealSection>
            ))}
          </div>
        </div>
      </section>

      {/* How It Works */}
      <section className="py-24 px-4 bg-white">
        <div className="max-w-4xl mx-auto">
          <RevealSection className="text-center mb-16">
            <span className="text-indigo-600 font-semibold text-sm uppercase tracking-widest">Simple Process</span>
            <h2 className="text-4xl font-extrabold text-gray-900 mt-3 mb-4">From Zero to Sent in 60 Seconds</h2>
            <p className="text-gray-500 text-lg">Four steps. That's all it takes.</p>
          </RevealSection>

          <div className="relative">
            {/* Vertical connector line */}
            <div className="absolute left-6 top-8 bottom-8 w-0.5 bg-gradient-to-b from-indigo-500 to-purple-500 hidden md:block" />

            <div className="space-y-8">
              {STEPS.map((step, i) => (
                <RevealSection key={step.label} delay={i * 120}>
                  <div className="flex gap-6 items-start group">
                    <div className="relative flex-shrink-0">
                      <div className="w-12 h-12 rounded-full bg-gradient-to-br from-indigo-500 to-purple-600 text-white flex items-center justify-center font-bold text-lg shadow-lg group-hover:scale-110 transition-transform z-10 relative">
                        {i + 1}
                      </div>
                      <div className="absolute inset-0 rounded-full bg-indigo-400 animate-ping opacity-0 group-hover:opacity-30" style={{ animationDuration: '1.5s' }} />
                    </div>
                    <div className="bg-gray-50 rounded-2xl p-6 flex-1 border border-gray-100 group-hover:border-indigo-200 transition-colors">
                      <h3 className="text-lg font-bold text-gray-900 mb-1">{step.label}</h3>
                      <p className="text-gray-500 text-sm leading-relaxed">{step.desc}</p>
                    </div>
                  </div>
                </RevealSection>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* Social Proof / CTA Banner */}
      <section className="py-20 px-4 bg-gradient-to-r from-indigo-600 to-purple-700 text-white relative overflow-hidden">
        <div className="hero-glow bg-white w-80 h-80 top-0 right-0 opacity-10" />
        <RevealSection className="max-w-3xl mx-auto text-center relative z-10">
          <h2 className="text-4xl font-extrabold mb-4">Ready to 10x Your Outreach?</h2>
          <p className="text-indigo-200 text-lg mb-8 max-w-xl mx-auto">
            Join sales professionals, founders, and agencies who use PitchPerfect to land more meetings every week.
          </p>
          {!isAuthenticated && (
            <Link
              href="/signup"
              className="inline-flex items-center gap-2 bg-white text-indigo-700 px-10 py-4 rounded-xl font-bold text-lg hover:bg-indigo-50 transition-all shadow-xl"
            >
              Start Free Today
              <span className="text-xl">→</span>
            </Link>
          )}
          {isAuthenticated && (
            <Link
              href="/generate"
              className="inline-flex items-center gap-2 bg-white text-indigo-700 px-10 py-4 rounded-xl font-bold text-lg hover:bg-indigo-50 transition-all shadow-xl"
            >
              Generate Your First Email
              <span className="text-xl">→</span>
            </Link>
          )}
        </RevealSection>
      </section>

      {/* FAQ Section */}
      <section className="py-24 px-4 bg-gray-50">
        <div className="max-w-3xl mx-auto">
          <RevealSection className="text-center mb-14">
            <span className="text-indigo-600 font-semibold text-sm uppercase tracking-widest">FAQ</span>
            <h2 className="text-4xl font-extrabold text-gray-900 mt-3 mb-4">Frequently Asked Questions</h2>
            <p className="text-gray-500 text-lg">Everything you need to know about PitchPerfect.</p>
          </RevealSection>

          <div className="space-y-3">
            {FAQS.map((faq, i) => (
              <RevealSection key={faq.q} delay={i * 60}>
                <FAQItem q={faq.q} a={faq.a} />
              </RevealSection>
            ))}
          </div>

          <RevealSection delay={200} className="text-center mt-12">
            <p className="text-gray-500">
              Still have questions?{' '}
              <a href="mailto:support@pitchperfect.ai" className="text-indigo-600 font-semibold hover:underline">
                Contact us
              </a>
            </p>
          </RevealSection>
        </div>
      </section>
    </div>
  );
}
