'use client';

import Link from 'next/link';

export default function TermsPage() {
  return (
    <div className="max-w-3xl mx-auto py-16 px-4">
      <div className="mb-10">
        <h1 className="text-4xl font-bold text-primary mb-3">Terms of Service</h1>
        <p className="text-gray-500 text-sm">Last updated: April 23, 2026</p>
      </div>

      <div className="space-y-10 text-gray-700 leading-relaxed">
        <section>
          <h2 className="text-xl font-semibold text-primary mb-3">1. Acceptance of Terms</h2>
          <p>
            By accessing or using PitchPerfect, you agree to be bound by these Terms of Service. If
            you do not agree to these terms, please do not use our service. We may update these terms
            from time to time and will notify you of material changes.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-primary mb-3">2. Description of Service</h2>
          <p>
            PitchPerfect provides an AI-powered email generation platform that helps users create
            professional pitch and outreach emails. The service is provided on a subscription basis
            with different plan tiers offering varying levels of usage.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-primary mb-3">3. Account Registration</h2>
          <p className="mb-3">To use PitchPerfect you must:</p>
          <ul className="list-disc list-inside space-y-2 pl-2">
            <li>Provide accurate and complete registration information</li>
            <li>Maintain the security of your account credentials</li>
            <li>Be at least 18 years of age</li>
            <li>Notify us immediately of any unauthorized use of your account</li>
          </ul>
          <p className="mt-3">
            You are responsible for all activity that occurs under your account.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-primary mb-3">4. Acceptable Use</h2>
          <p className="mb-3">You agree not to use PitchPerfect to:</p>
          <ul className="list-disc list-inside space-y-2 pl-2">
            <li>Generate spam, unsolicited bulk email, or deceptive content</li>
            <li>Violate any applicable laws or regulations</li>
            <li>Infringe on the intellectual property rights of others</li>
            <li>Attempt to gain unauthorized access to our systems</li>
            <li>Reverse engineer or copy our AI models or proprietary technology</li>
          </ul>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-primary mb-3">5. Subscription and Billing</h2>
          <p>
            Paid plans are billed on a monthly basis. You may cancel your subscription at any time;
            cancellation takes effect at the end of the current billing period. We do not offer
            refunds for partial billing periods except where required by law.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-primary mb-3">6. Intellectual Property</h2>
          <p>
            You retain ownership of the content you input into PitchPerfect. The emails generated by
            our AI are provided for your use. PitchPerfect retains all rights to its platform,
            technology, and AI models. You may not reproduce, distribute, or create derivative works
            from our platform without express written permission.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-primary mb-3">7. Disclaimer of Warranties</h2>
          <p>
            PitchPerfect is provided "as is" without warranty of any kind. We do not guarantee that
            the service will be uninterrupted, error-free, or that AI-generated content will meet
            your specific requirements. Use of generated content is at your own discretion and risk.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-primary mb-3">8. Limitation of Liability</h2>
          <p>
            To the maximum extent permitted by law, PitchPerfect shall not be liable for any
            indirect, incidental, special, or consequential damages arising from your use of or
            inability to use the service, even if we have been advised of the possibility of such
            damages.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-primary mb-3">9. Termination</h2>
          <p>
            We reserve the right to suspend or terminate your account at our discretion if you
            violate these terms. You may delete your account at any time from your profile settings.
            Upon termination, your right to use the service ceases immediately.
          </p>
        </section>

        <section>
          <h2 className="text-xl font-semibold text-primary mb-3">10. Contact</h2>
          <p>
            For questions about these Terms of Service, please{' '}
            <Link href="/contact" className="text-secondary hover:underline">
              contact us
            </Link>
            .
          </p>
        </section>
      </div>
    </div>
  );
}
